### ISSUE TITLE
support go-tuf v1?

### ISSUE THREAD

**Issue by jku** [theupdateframework/tuf-conformance#24]
* There is a client wrapper for go-tuf (v2) already
* One of the most widely used tuf clients is the one in cosign: it uses go-tuf v1
* The goal is for cosign to use go-tuf v2 in future

The question is: _would supporting both go-tuf versions in the conformance suite be useful in making that transition safer and easier?_

If yes, then we should consider making a client wrapper for go-tuf v1

**Comment by AdamKorcz** [comment]
@haydentherapper @cpanato @bobcallaway Do you have thoughts on this?

**Comment by haydentherapper** [comment]
Due to the proliferation of Cosign throughout Sigstore infra, we also have it used in sigstore/scaffolding, to set up private TUF repositories. Also note https://github.com/sigstore/cosign/issues/3548 is the issue for adopting the new Sigstore TUF client / go-tuf v2 in Cosign.

The plan is to fully adopt go-tuf v2 through the new Sigstore TUF client in the coming months. If the conformance test suite found that go-tuf v1 is not compliant, I wouldn't expect the maintainers to fix those non-compliance issues, since I'd assume they'd just point us to go-tuf v2. I'm OK excluding go-tuf v1 from the suite, from Sigstore's perspective.

**Comment by jku** [comment]
Let's go with that, closing
